Add code examples of close event
fergald/explainer-messageport-close pull request #2
Opened 2024-01-11 06:10 UTC by nononokam

I would like to add code examples of close event to explainer.
This is the [context](https://groups.google.com/a/chromium.org/g/blink-dev/c/enQs5VEdOmU/m/gFFd75aXBgAJ).

2024-01-11 09:53 UTC, fergald requested changes

2024-01-11 09:53 UTC, fergald commented on README.md
> +this `close` event is used as follows:
Capital T for "this".

2024-01-11 09:53 UTC, fergald commented on README.md
> +}
Maybe add something like 

```
// Free up resources associated with the port.
...
```

2024-01-11 09:53 UTC, fergald commented on README.md
> +    console.log("portA has been closed.");
indent 2 spaces.

2024-01-11 11:03 UTC, nononokam commented
Thank you for review! I worked on your comments.

2024-01-12 00:59 UTC, fergald approved these changes
Thanks!

2024-01-12 00:59 UTC, merged